name: Sync Repository to Public Mirror

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force sync all branches'
        required: false
        default: 'true'
        type: boolean
      public_repo_name:
        description: 'Public repository name (leave empty to auto-derive by removing "-private")'
        required: false
        type: string

jobs:
  call-sync-workflow:
    uses: thoughtspot/workflows/.github/workflows/sync-to-public-mirror.yml@c19c7b395533a67a484bb86bd497aa71ed279a07
    with:
      force_sync: ${{ github.event.inputs.force_sync == 'true' }}
      public_repo_name: ${{ github.event.inputs.public_repo_name || '' }}
    secrets:
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
